<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Serves a stored database dump to the agent's `curl` during an import.
 *
 * Reachable only through Laravel signed URLs generated by
 * DatabaseImportService (unguessable UUID filename + signature + 1-hour
 * expiry), so no session or role check applies — the signature is the
 * credential. Streamed from disk; dumps can be up to 1 GB.
 */
class DumpDownloadController extends Controller
{
    public function __invoke(Request $request, string $dump): StreamedResponse
    {
        abort_unless(preg_match('/^[0-9a-f-]{36}\.sql$/', $dump) === 1, 404);
        abort_unless(Storage::exists("dumps/{$dump}"), 404);

        return Storage::response("dumps/{$dump}", 'dump.sql', [
            'Content-Type' => 'application/sql',
        ]);
    }
}
