#!/usr/bin/env bash
#
# Velink agent installer.
#
# Usage (generated by the panel's "Add Server" page, which fills --panel and
# --gateway from the panel's own configured domain — no domain is hardcoded):
#   curl -fsSL https://<your-panel-domain>/install/agent.sh | sudo bash -s -- \
#       --token=<TOKEN> --server-id=<ID> --panel=https://<your-panel-domain>
#
# Flags:
#   --token       per-server enrollment token (required)
#   --server-id   this server's panel ID (required)
#   --panel       panel HTTP base URL (required, e.g. https://panel.example.com)
#   --gateway     gateway WSS base URL (optional; defaults to --panel with a
#                 websocket scheme, e.g. --panel https://x.io -> wss://x.io)
#   --version     agent version to install (default: latest)
#   --binary-url  explicit binary URL (overrides --panel-based download)
#   --insecure    skip TLS verification (dev only)
#
set -euo pipefail

# ─── Colour helpers ────────────────────────────────────────────────────────────
if [ -t 1 ] && command -v tput >/dev/null 2>&1; then
    BOLD="$(tput bold)"
    RED="$(tput setaf 1)"
    GREEN="$(tput setaf 2)"
    YELLOW="$(tput setaf 3)"
    CYAN="$(tput setaf 6)"
    RESET="$(tput sgr0)"
else
    BOLD="" RED="" GREEN="" YELLOW="" CYAN="" RESET=""
fi

STEP=0
TOTAL=7

_header() {
    echo ""
    echo "${BOLD}${CYAN}╔══════════════════════════════════════════════════╗${RESET}"
    printf "${BOLD}${CYAN}║${RESET}  %-48s${BOLD}${CYAN}║${RESET}\n" "$1"
    echo "${BOLD}${CYAN}╚══════════════════════════════════════════════════╝${RESET}"
}

step() {
    STEP=$((STEP + 1))
    echo ""
    echo "${BOLD}[${STEP}/${TOTAL}]${RESET} ${CYAN}▶ ${*}${RESET}"
}

ok()   { echo "      ${GREEN}✓${RESET}  ${*}"; }
info() { echo "      ${YELLOW}→${RESET}  ${*}"; }
die()  { echo ""; echo "${RED}✗  ERROR: ${*}${RESET}" >&2; exit 1; }

# ─── Parse flags ───────────────────────────────────────────────────────────────
TOKEN=""
SERVER_ID=""
GATEWAY_URL=""
PANEL_URL=""
VERSION="latest"
BINARY_URL=""
INSECURE="0"

for arg in "$@"; do
    case "$arg" in
        --token=*)      TOKEN="${arg#*=}" ;;
        --server-id=*)  SERVER_ID="${arg#*=}" ;;
        --gateway=*)    GATEWAY_URL="${arg#*=}" ;;
        --panel=*)      PANEL_URL="${arg#*=}" ;;
        --version=*)    VERSION="${arg#*=}" ;;
        --binary-url=*) BINARY_URL="${arg#*=}" ;;
        --insecure)     INSECURE="1" ;;
        *) die "unknown argument: $arg" ;;
    esac
done

# ─── Resolve URLs from parameters ────────────────────────────────────────────
# No domain is baked into this script. The panel injects --panel (and usually
# --gateway) from its own configured domain, so a custom domain just works. When
# --gateway is omitted, derive it from --panel by swapping the scheme to a
# websocket scheme (https -> wss, http -> ws).
[ -n "$PANEL_URL" ] || die "--panel is required (the panel's install command sets it)"
if [ -z "$GATEWAY_URL" ]; then
    case "$PANEL_URL" in
        https://*) GATEWAY_URL="wss://${PANEL_URL#https://}" ;;
        http://*)  GATEWAY_URL="ws://${PANEL_URL#http://}" ;;
        *)         GATEWAY_URL="wss://${PANEL_URL}" ;;
    esac
fi
PANEL_URL="${PANEL_URL%/}"
GATEWAY_URL="${GATEWAY_URL%/}"

# ─── Banner ────────────────────────────────────────────────────────────────────
clear 2>/dev/null || true
echo ""
echo "${BOLD}  Velink Agent Installer${RESET}"
echo "  ──────────────────────────────────────────────────"
echo "  This script will perform the following actions:"
echo ""
echo "  ${GREEN}1.${RESET} Verify system requirements (root, OS, architecture)"
echo "  ${GREEN}2.${RESET} Detect OS & CPU architecture"
echo "  ${GREEN}3.${RESET} Download the Velink agent binary to /usr/local/bin/"
echo "  ${GREEN}4.${RESET} Write agent config (token, gateway URL) to /etc/velink/"
echo "  ${GREEN}5.${RESET} Install a systemd service unit (velink-agent.service)"
echo "  ${GREEN}6.${RESET} Register with the panel & arm full-stack provisioning"
echo "  ${GREEN}7.${RESET} Enable & start the service via systemctl"
echo ""
echo "  ${YELLOW}Files created / modified:${RESET}"
echo "    /usr/local/bin/velink-agent      ← agent binary (executable)"
echo "    /etc/velink/agent.env            ← config (chmod 600, root-only)"
echo "    /etc/systemd/system/velink-agent.service"
echo ""
echo "  ${YELLOW}Network connections made:${RESET}"
echo "    ${PANEL_URL%/}/install/bin/...   ← binary download"
echo "    ${GATEWAY_URL}                   ← WebSocket to panel (at runtime)"
echo ""
echo "  ──────────────────────────────────────────────────"

BIN_PATH="/usr/local/bin/velink-agent"
ENV_DIR="/etc/velink"
ENV_FILE="${ENV_DIR}/agent.env"
UNIT_FILE="/etc/systemd/system/velink-agent.service"

# ─── Step 1: Prerequisites ─────────────────────────────────────────────────────
step "Checking prerequisites"

[ "$(id -u)" -eq 0 ] || die "must run as root (use sudo)"
ok "Running as root"

[ -n "$TOKEN" ]     || die "--token is required"
ok "Enrollment token present"

[ -n "$SERVER_ID" ] || die "--server-id is required"
ok "Server ID present (${SERVER_ID})"

command -v curl >/dev/null 2>&1 || die "curl is required but not found"
ok "curl is available"

# ─── Step 2: Detect platform ───────────────────────────────────────────────────
step "Detecting system platform"

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ok "Operating system: ${OS}"

case "$(uname -m)" in
    x86_64|amd64)    ARCH="amd64" ;;
    aarch64|arm64)   ARCH="arm64" ;;
    *) die "unsupported architecture: $(uname -m)" ;;
esac
ok "CPU architecture: ${ARCH}"

if [ -f /etc/os-release ]; then
    DISTRO_NAME="$(. /etc/os-release && echo "${PRETTY_NAME:-unknown}")"
    ok "Distribution: ${DISTRO_NAME}"
fi

if [ -z "$BINARY_URL" ]; then
    BINARY_URL="${PANEL_URL%/}/install/bin/agent-${OS}-${ARCH}-${VERSION}"
fi
info "Binary URL: ${BINARY_URL}"

# ─── Step 3: Download agent binary ────────────────────────────────────────────
step "Downloading Velink agent binary"
info "Source : ${BINARY_URL}"
info "Destination : ${BIN_PATH}"

CURL_OPTS=(-fL --progress-bar)
[ "$INSECURE" = "1" ] && CURL_OPTS+=(-k)

TMP="$(mktemp)"
# Show download progress on stderr so it's visible even when piped
curl "${CURL_OPTS[@]}" "$BINARY_URL" -o "$TMP" 2>&1 || die "binary download failed — check your connection or panel URL"
chmod 0755 "$TMP"
install -m 0755 "$TMP" "$BIN_PATH"
rm -f "$TMP"

AGENT_SIZE="$(du -sh "$BIN_PATH" 2>/dev/null | cut -f1)"
ok "Binary installed to ${BIN_PATH} (${AGENT_SIZE})"

# ─── Step 4: Write agent configuration ────────────────────────────────────────
step "Writing agent configuration"
info "Directory  : ${ENV_DIR}"
info "Config file: ${ENV_FILE}  (mode 600, readable only by root)"
info "Values being written:"
info "  AGENT_GATEWAY_URL = ${GATEWAY_URL}"
info "  AGENT_SERVER_ID   = ${SERVER_ID}"
info "  AGENT_TOKEN       = [hidden]"
info "  AGENT_HEARTBEAT   = 30"
info "  AGENT_INSECURE    = ${INSECURE}"

mkdir -p "$ENV_DIR"
(umask 177; cat > "$ENV_FILE" <<EOF
AGENT_GATEWAY_URL=${GATEWAY_URL}
AGENT_TOKEN=${TOKEN}
AGENT_SERVER_ID=${SERVER_ID}
AGENT_HEARTBEAT=30
AGENT_INSECURE=${INSECURE}
EOF
)
ok "Config written and locked to root (chmod 600)"

# ─── Step 5: Install systemd service ──────────────────────────────────────────
step "Installing systemd service unit"
info "Unit file: ${UNIT_FILE}"
info "Service name: velink-agent.service"
info "Run as: root (agent provisions packages & services on this VM)"
info "Restart policy: always (restarts 5s after crash)"

cat > "$UNIT_FILE" <<'EOF'
[Unit]
Description=Velink agent
Documentation=https://github.com/velink
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/velink/agent.env
ExecStart=/usr/local/bin/velink-agent
Restart=always
RestartSec=5
# The agent provisions packages/services, so it runs privileged.
User=root
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=no

[Install]
WantedBy=multi-user.target
EOF

ok "Service unit written to ${UNIT_FILE}"

# ─── Step 6: Register with panel & arm provisioning ───────────────────────────
step "Registering with the panel"

if command -v systemctl >/dev/null 2>&1; then
    info "Running: systemctl daemon-reload"
    systemctl daemon-reload
    ok "systemd daemon reloaded"

    info "Running: systemctl enable velink-agent.service"
    systemctl enable velink-agent.service >/dev/null 2>&1
    ok "Service enabled to start on boot"
fi

# Tell the panel this server was (re)installed so it provisions the full stack
# the moment the agent connects. Done before the agent starts so the panel sees
# a clean slate; the actual install jobs are dispatched by the panel on connect.
PROVISION_URL="${PANEL_URL%/}/install/provision"
info "Arming provisioning: ${PROVISION_URL}"
PROVISION_OPTS=(-fsS -X POST -H "Content-Type: application/json")
[ "$INSECURE" = "1" ] && PROVISION_OPTS+=(-k)
if curl "${PROVISION_OPTS[@]}" "$PROVISION_URL" \
        -d "{\"server_id\":\"${SERVER_ID}\",\"token\":\"${TOKEN}\"}" >/dev/null 2>&1; then
    ok "Panel armed — full stack will install when the agent connects"
else
    info "Could not reach panel to arm provisioning"
    info "(a brand-new server still auto-provisions on first connect)"
fi

# ─── Step 7: Start the agent ──────────────────────────────────────────────────
step "Starting velink-agent service"

if command -v systemctl >/dev/null 2>&1; then
    info "Running: systemctl restart velink-agent.service"
    systemctl restart velink-agent.service
    ok "Service started"

    # Brief pause so the service has time to connect before we show status
    sleep 2

    echo ""
    echo "  ${BOLD}Service status:${RESET}"
    echo "  ──────────────────────────────────────────────────"
    systemctl --no-pager --full status velink-agent.service || true
else
    info "systemctl not found — start the agent manually:"
    info "  ${BIN_PATH}"
fi

# ─── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "${BOLD}${GREEN}  ══════════════════════════════════════════════════${RESET}"
echo "${BOLD}${GREEN}  ✓  Installation complete!${RESET}"
echo "${BOLD}${GREEN}  ══════════════════════════════════════════════════${RESET}"
echo ""
echo "  The server should appear ${GREEN}online${RESET} in the panel within a few seconds."
echo ""
echo "  Useful commands:"
echo "    systemctl status  velink-agent   ← check agent status"
echo "    journalctl -u velink-agent -f    ← follow agent logs"
echo "    systemctl restart velink-agent   ← restart agent"
echo "    systemctl stop    velink-agent   ← stop agent"
echo ""
