#!/usr/bin/env bash
#
# Velink agent installer.
#
# Usage (generated by the panel's "Add Server" page):
#   curl -fsSL https://panel.selepaskerja.id/install/agent.sh | sudo bash -s -- \
#       --token=<TOKEN> --server-id=<ID>
#
# Flags:
#   --token       per-server enrollment token (required)
#   --server-id   this server's panel ID (required)
#   --gateway     gateway WSS base URL (optional override, default: ws://panel.selepaskerja.id:8080)
#   --panel       panel HTTP base URL (optional override, default: https://panel.selepaskerja.id)
#   --version     agent version to install (default: latest)
#   --binary-url  explicit binary URL (overrides --panel-based download)
#   --insecure    skip TLS verification (dev only)
#
set -euo pipefail

TOKEN=""
SERVER_ID=""
GATEWAY_URL="ws://panel.selepaskerja.id:8080"
PANEL_URL="https://panel.selepaskerja.id"
VERSION="latest"
BINARY_URL=""
INSECURE="0"

BIN_PATH="/usr/local/bin/velink-agent"
ENV_DIR="/etc/velink"
ENV_FILE="${ENV_DIR}/agent.env"
UNIT_FILE="/etc/systemd/system/velink-agent.service"

log()  { echo "[velink] $*"; }
die()  { echo "[velink] ERROR: $*" >&2; exit 1; }

for arg in "$@"; do
    case "$arg" in
        --token=*)      TOKEN="${arg#*=}" ;;
        --server-id=*)  SERVER_ID="${arg#*=}" ;;
        --gateway=*)    GATEWAY_URL="${arg#*=}" ;;
        --panel=*)      PANEL_URL="${arg#*=}" ;;
        --version=*)    VERSION="${arg#*=}" ;;
        --binary-url=*) BINARY_URL="${arg#*=}" ;;
        --insecure)     INSECURE="1" ;;
        *) die "unknown argument: $arg" ;;
    esac
done

[ "$(id -u)" -eq 0 ] || die "must run as root (use sudo)"
[ -n "$TOKEN" ]     || die "--token is required"
[ -n "$SERVER_ID" ] || die "--server-id is required"

# Detect platform.
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$(uname -m)" in
    x86_64|amd64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    *) die "unsupported architecture: $(uname -m)" ;;
esac

if [ -z "$BINARY_URL" ]; then
    BINARY_URL="${PANEL_URL%/}/install/bin/agent-${OS}-${ARCH}-${VERSION}"
fi

CURL_OPTS=(-fsSL)
[ "$INSECURE" = "1" ] && CURL_OPTS+=(-k)

log "downloading agent binary: ${BINARY_URL}"
TMP="$(mktemp)"
curl "${CURL_OPTS[@]}" "$BINARY_URL" -o "$TMP" || die "download failed"
chmod 0755 "$TMP"
install -m 0755 "$TMP" "$BIN_PATH"
rm -f "$TMP"
log "installed binary to ${BIN_PATH}"

# Write config.
mkdir -p "$ENV_DIR"
umask 077
cat > "$ENV_FILE" <<EOF
AGENT_GATEWAY_URL=${GATEWAY_URL}
AGENT_TOKEN=${TOKEN}
AGENT_SERVER_ID=${SERVER_ID}
AGENT_HEARTBEAT=30
AGENT_INSECURE=${INSECURE}
EOF
chmod 0600 "$ENV_FILE"
log "wrote config to ${ENV_FILE}"

# Install systemd unit.
cat > "$UNIT_FILE" <<'EOF'
[Unit]
Description=Velink agent
Documentation=https://github.com/velink
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/velink/agent.env
ExecStart=/usr/local/bin/velink-agent
Restart=always
RestartSec=5
# The agent provisions packages/services, so it runs privileged.
User=root
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=no

[Install]
WantedBy=multi-user.target
EOF
log "installed systemd unit to ${UNIT_FILE}"

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    systemctl enable --now velink-agent.service
    log "agent service started"
    systemctl --no-pager --full status velink-agent.service || true
else
    log "systemctl not found; start the agent manually: ${BIN_PATH}"
fi

log "done. The server should appear online in the panel shortly."
